import type { Lang } from "../cognitive/types";
// Authored language banks; editorial/psychometric validation remains pending.
const categories = {
  fr: [
    ["pomme", "poire", "prune", "marteau"],
    ["rouge", "bleu", "vert", "carré"],
    ["courir", "marcher", "sauter", "penser"],
    ["cuillère", "fourchette", "couteau", "oreiller"],
    ["hêtre", "chêne", "sapin", "nuage"],
    ["triangle", "cercle", "carré", "mélodie"],
    ["lundi", "mardi", "jeudi", "janvier"],
    ["guitare", "flûte", "piano", "lampe"],
    ["joie", "peur", "colère", "fenêtre"],
    ["nager", "ramer", "plonger", "tricoter"],
    ["gramme", "kilogramme", "tonne", "litre"],
    ["nord", "sud", "ouest", "demain"],
    ["riz", "blé", "avoine", "granit"],
    ["chat", "chien", "cheval", "truite"],
    ["maison", "cabane", "immeuble", "cascade"],
    ["additionner", "soustraire", "multiplier", "peindre"],
    ["rivière", "ruisseau", "fleuve", "sentier"],
    ["murmurer", "parler", "crier", "observer"],
    ["soie", "coton", "laine", "cuivre"],
    ["cercle", "sphère", "disque", "triangle"],
  ],
  en: [
    ["apple", "pear", "plum", "hammer"],
    ["red", "blue", "green", "square"],
    ["run", "walk", "jump", "think"],
    ["spoon", "fork", "knife", "pillow"],
    ["beech", "oak", "pine", "cloud"],
    ["triangle", "circle", "square", "melody"],
    ["Monday", "Tuesday", "Thursday", "January"],
    ["guitar", "flute", "piano", "lamp"],
    ["joy", "fear", "anger", "window"],
    ["swim", "row", "dive", "knit"],
    ["gram", "kilogram", "tonne", "litre"],
    ["north", "south", "west", "tomorrow"],
    ["rice", "wheat", "oats", "granite"],
    ["cat", "dog", "horse", "trout"],
    ["house", "hut", "building", "waterfall"],
    ["add", "subtract", "multiply", "paint"],
    ["river", "stream", "brook", "path"],
    ["whisper", "speak", "shout", "observe"],
    ["silk", "cotton", "wool", "copper"],
    ["circle", "sphere", "disc", "triangle"],
  ],
};
const synonyms = {
  fr: [
    ["Ce passage est bref.", "bref", "court", "bruyant", "lointain", "sombre"],
    [
      "Son explication est limpide.",
      "limpide",
      "claire",
      "liquide",
      "longue",
      "fragile",
    ],
    [
      "La boîte est vide.",
      "vide",
      "sans contenu",
      "lourde",
      "fermée",
      "pleine",
    ],
    ["Elle demeure calme.", "demeure", "reste", "habite", "voyage", "tombe"],
    [
      "Le résultat est exact.",
      "exact",
      "correct",
      "rapide",
      "probable",
      "récent",
    ],
    [
      "Il avance avec prudence.",
      "prudence",
      "précaution",
      "hâte",
      "colère",
      "certitude",
    ],
    [
      "Cette ressource est rare.",
      "rare",
      "peu fréquente",
      "inutile",
      "ancienne",
      "fragile",
    ],
    [
      "Une issue est possible.",
      "issue",
      "solution",
      "entrée",
      "erreur",
      "habitude",
    ],
    [
      "Le tissu est souple.",
      "souple",
      "flexible",
      "épais",
      "rugueux",
      "solide",
    ],
    [
      "Son avis est nuancé.",
      "nuancé",
      "avec des distinctions",
      "unanime",
      "définitif",
      "bref",
    ],
    [
      "Le sentier est étroit.",
      "étroit",
      "peu large",
      "peu long",
      "très haut",
      "très lisse",
    ],
    [
      "Il refuse cette offre.",
      "refuse",
      "décline",
      "oublie",
      "attend",
      "réclame",
    ],
    [
      "Le changement est progressif.",
      "progressif",
      "graduel",
      "brusque",
      "complet",
      "impossible",
    ],
    [
      "Cette réponse est pertinente.",
      "pertinente",
      "adaptée au sujet",
      "très courte",
      "très polie",
      "ancienne",
    ],
    [
      "Les deux récits concordent.",
      "concordent",
      "s’accordent",
      "s’opposent",
      "s’arrêtent",
      "s’allongent",
    ],
    [
      "Elle anticipe le départ.",
      "anticipe",
      "prévoit",
      "annule",
      "ignore",
      "retarde",
    ],
    [
      "La tâche est achevée.",
      "achevée",
      "terminée",
      "commencée",
      "difficile",
      "répétée",
    ],
    [
      "Son ton est discret.",
      "discret",
      "peu voyant",
      "très aigu",
      "pressant",
      "joyeux",
    ],
    [
      "Le lien est évident.",
      "évident",
      "manifeste",
      "inexistant",
      "fragile",
      "ancien",
    ],
    [
      "Il examine le détail.",
      "examine",
      "observe attentivement",
      "efface",
      "invente",
      "cache",
    ],
  ],
  en: [
    ["The passage is brief.", "brief", "short", "loud", "distant", "dark"],
    [
      "Her explanation is clear.",
      "clear",
      "easy to understand",
      "empty",
      "long",
      "fragile",
    ],
    [
      "The box is empty.",
      "empty",
      "without contents",
      "heavy",
      "closed",
      "full",
    ],
    ["She remains calm.", "remains", "stays", "lives", "travels", "falls"],
    [
      "The result is accurate.",
      "accurate",
      "correct",
      "quick",
      "probable",
      "recent",
    ],
    [
      "He proceeds with caution.",
      "caution",
      "care",
      "haste",
      "anger",
      "certainty",
    ],
    [
      "This resource is scarce.",
      "scarce",
      "in short supply",
      "useless",
      "ancient",
      "fragile",
    ],
    [
      "There is a way out of this problem.",
      "way out",
      "solution",
      "entrance",
      "mistake",
      "habit",
    ],
    [
      "The material is flexible.",
      "flexible",
      "easy to bend",
      "thick",
      "rough",
      "rigid",
    ],
    [
      "Her view is nuanced.",
      "nuanced",
      "recognizing distinctions",
      "unanimous",
      "final",
      "brief",
    ],
    [
      "The path is narrow.",
      "narrow",
      "not wide",
      "not long",
      "very high",
      "very smooth",
    ],
    [
      "He declines the offer.",
      "declines",
      "refuses",
      "forgets",
      "awaits",
      "requests",
    ],
    [
      "The change is gradual.",
      "gradual",
      "progressive",
      "sudden",
      "complete",
      "impossible",
    ],
    [
      "The answer is relevant.",
      "relevant",
      "related to the topic",
      "very short",
      "very polite",
      "old",
    ],
    [
      "The two accounts agree.",
      "agree",
      "are consistent",
      "contradict",
      "stop",
      "lengthen",
    ],
    [
      "She anticipates the departure.",
      "anticipates",
      "foresees",
      "cancels",
      "ignores",
      "delays",
    ],
    [
      "The task is complete.",
      "complete",
      "finished",
      "started",
      "difficult",
      "repeated",
    ],
    [
      "The design is understated.",
      "understated",
      "subtle",
      "sharp",
      "urgent",
      "cheerful",
    ],
    [
      "The connection is obvious.",
      "obvious",
      "plain to see",
      "nonexistent",
      "fragile",
      "old",
    ],
    [
      "He scrutinizes the detail.",
      "scrutinizes",
      "examines closely",
      "erases",
      "invents",
      "conceals",
    ],
  ],
};
export function verbalItem(lang: Lang, k: number) {
  const fr = lang === "fr";
  if (k < 40) {
    const row = categories[lang][k - 20];
    return {
      subtype: "categorization",
      prompt: fr
        ? "Quel mot appartient le moins à la même catégorie que les trois autres ?"
        : "Which word belongs least to the category shared by the other three?",
      correct: row[3],
      others: row.slice(0, 3),
      explanation: fr
        ? `${row.slice(0, 3).join(", ")} partagent une catégorie que ${row[3]} ne partage pas.`
        : `${row.slice(0, 3).join(", ")} share a category that ${row[3]} does not.`,
    };
  }
  const row = synonyms[lang][k - 40];
  return {
    subtype: "contextual-meaning",
    prompt: fr
      ? `${row[0]} Quel sens a « ${row[1]} » ici ?`
      : `${row[0]} What does “${row[1]}” mean here?`,
    correct: row[2],
    others: row.slice(3),
    explanation: row[2],
  };
}
